server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emp_mg
    username: postgres
    password: Shkna1368


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true


minio:
  bucket:
    name: epm
  default:
    folder: "/"
  access:
    name: minioadmin
    secret: minioadmin

  url: http://127.0.0.1:9000


---
logging:
  file:
    path: ./
    name: logfile.log


---
spring:
  boot:
    admin:
      api-path: /instances
      url: http://localhost:8090
      client:
        url: http://localhost:8090


---
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

