


server:
  port: 8181
---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: postgres



  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false
---
server:
  tomcat:
    threads:
      max: 1000
---

spring:
  datasource:
    hikari:
      connection-timeout : 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 150 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 200 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.


---
logging:
  level:
    com:
    zaxxer:
      hikari:
        HikariConfig: DEBUG

---
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG