server:
  port: 8090

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:~/emp_mg;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update