server:
  port: 0
  servlet:
    context-path: /employeeservice
---

springdoc :

  enable-native-support: true

  swagger-ui:
    path: /swagger

  api-docs:
    path: /api-docs
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee-service
    username: postgres
    password: postgres


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

---
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 15MB

---

spring:
  application:
    name: employee-service
eureka:
  instance:
    instance-id:  ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
