scrape_configs:
  - job_name: 'Kurdestan-Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8090']
        labels:
          application: 'My Kurdestan Spring Boot Application'