server:
  port: 7071
  servlet:
    context-path: /postemployeeservice
---

springdoc:
  swagger-ui:
    path: /swagger

  api-docs:
    path: /api-docs
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post-employee-service
    username: postgres
    password: Shkna1368


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

---
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 15MB

---
grpc:
   client:
     myService:
           address : "static://127.0.0.1:9090"
           negotiation-type: plaintext


---
spring:
  boot:
    admin:
      api-path: /instances
      url: http://localhost:7071/postemployeeservice
      client:
        url: http://localhost:7071/postemployeeservice


---
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always